### ISSUE TITLE
Invalid value Europe/Bratislava in field agency_timezone

### ISSUE THREAD

**Issue by bdferris** [google/transitfeed#267]
_From [ris.d...@gmail.com](https://code.google.com/u/111017630767444300061/) on November 29, 2010 11:22:26_

Here is the error as reported by feedvalidator:

Invalid value Europe/Bratislava in field agency_timezone
"Europe/Bratislava" is not a common timezone name according to pytz version 2010h
in line 2 of agency.txt

But the TimeZone is listed at http://en.wikipedia.org/wiki/List_of_tz_zones as suggested in GTFS.

_Original issue: http://code.google.com/p/googletransitdatafeed/issues/detail?id=267_

**Comment by argilo** [comment]
I recently encountered this problem for OC Transpo, which is using America/Montreal as its timezone. I worked around the problem by passing `problems=transitfeed.problems.ProblemReporter()` into `transitfeed.Loader`:

https://github.com/argilo/BusFollower/commit/a72f9d2c513f702bb4becebc9881379f27857500

The base `ProblemReporter` class uses `SimpleProblemAccumulator` as its accumulator, and `SimpleProblemAccumulator` prints errors to the console instead of raising exceptions.
